version: '2'

services:
  srv:
    image: emarcs/nginx-cors
    ports:
      - 35001:80
    volumes:
      - ./default-node:/etc/nginx/sites-available/default
    links:
      - node:node_app
  node:
    image: node:4-onbuild
    volumes:
      - ./example:/usr/src/app
